on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        node: [20]

    steps:
      - uses: actions/checkout@v3
      - run: npm install   
      - run: npm run deploy

  
